ParserRuleContext.getChildCount() now returns 0 if self.children is None
Otherwise, you get the following error when a listener executes ctx.getText() on a rule that allows a blank line:
    TypeError: object of type 'NoneType' has no len()